### ISSUE TITLE
WIKI or Examples

### ISSUE THREAD

**Issue by karfam** [asv-soft/asv-mavlink#60]
Hello
I am trying to build some simple examples using asv-mavlink.
ie Connect to a com port and display device position in a map.

Would something like this work?
```
mavlinkConnection = new MavlinkV2Connection($"serial:{selectedPort}:57600", p =>
{
    MavlinkV2Connection.RegisterDefaultDialects(p);
});
        

mavlinkConnection.Subscribe(packet =>
{
    if (packet is GpsRawIntPacket gpsRawIntPacket)
    {
       
    }
});
```

**Comment by asv-soft-u01** [comment]
Hello!
Yes, all seems fine and should work.

**Comment by karfam** [comment]
Thanks for response Alexander!

Is there a different way like connecting to the com port and listen only for specific message and not subscribing to everything?

**Comment by karfam** [comment]
Thanks for response Alexander!

Is there a different way like connecting to the com port and listen only for spesific message?

**Comment by asv-soft-u01** [comment]
Since you don't specify how mavlinkConnection is used you can't filter out unnecessary packets. If you are trying to develop a new device or microservice that will work in MAVLink network, then you probably need to create a new implementation for it. MavlinkV2Connection is just a connection between devices in the network, all it has is a DataStream of some sort.

You can check out MavlinkRouter class in our repository, it can do more than a simple connection, maybe that will help.

Best regards,
Aleksandr.

**Comment by asv-soft-u01** [comment]
Hello!

Was your problem resolved? If so, then can we close this issue?

Best regards,
Aleksandr.

**Comment by karfam** [comment]
Hello Sir
Unfortunately, the lack of basic documentation and examples made me switch to Missionplanner, even though asv-Mavlink looks very polished (but not for beginners)

Best Regards
Theodoros

**Comment by karfam** [comment]
Hello Sir
Unfortunately, the lack of documentation and examples made me
